# Generated by Django 5.0.6 on 2026-08-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akademik', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_nilai', models.CharField(choices=[('HARIAN', 'Ulangan Harian'), ('UTS', 'Ujian Tengah Semester'), ('UAS', 'Ujian Akhir Semester'), ('TUGAS', 'Tugas')], default='HARIAN', max_length=10, verbose_name='Jenis Nilai')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nilai')),
                ('semester', models.CharField(choices=[('GANJIL', 'Ganjil'), ('GENAP', 'Genap')], default='GANJIL', max_length=10, verbose_name='Semester')),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=15, verbose_name='Tahun Ajaran')),
                ('tanggal_input', models.DateField(auto_now_add=True, verbose_name='Tanggal Input')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='akademik.matapelajaran', verbose_name='Mata Pelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='siswa.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
                'ordering': ['-tanggal_input'],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prestasi', models.CharField(max_length=200, verbose_name='Nama Prestasi/Lomba')),
                ('tingkat', models.CharField(choices=[('SEKOLAH', 'Sekolah'), ('KECAMATAN', 'Kecamatan'), ('KABUPATEN', 'Kabupaten/Kota'), ('PROVINSI', 'Provinsi'), ('NASIONAL', 'Nasional')], default='SEKOLAH', max_length=15, verbose_name='Tingkat')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('keterangan', models.CharField(blank=True, default='', max_length=255, verbose_name='Keterangan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='siswa.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Prestasi',
                'verbose_name_plural': 'Prestasi',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('SAKIT', 'Sakit'), ('IZIN', 'Izin'), ('ALPA', 'Alpa/Tanpa Keterangan')], default='HADIR', max_length=10, verbose_name='Status')),
                ('keterangan', models.CharField(blank=True, default='', max_length=255, verbose_name='Keterangan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='siswa.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Kehadiran',
                'verbose_name_plural': 'Kehadiran',
                'ordering': ['-tanggal'],
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
    ]
