# Generated by Django 5.0.6 on 2026-08-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=25, unique=True, verbose_name='NIP')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('no_hp', models.CharField(blank=True, default='', max_length=20, verbose_name='No. HP')),
                ('alamat', models.CharField(blank=True, default='', max_length=255, verbose_name='Alamat')),
                ('tanggal_bergabung', models.DateField(blank=True, null=True, verbose_name='Tanggal Bergabung')),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
                'ordering': ['nama'],
            },
        ),
    ]
