# Generated by Django 5.0.6 on 2026-08-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20, unique=True, verbose_name='NIS')),
                ('nisn', models.CharField(max_length=20, unique=True, verbose_name='NISN')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('tempat_lahir', models.CharField(blank=True, default='', max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('alamat', models.CharField(blank=True, default='', max_length=255, verbose_name='Alamat')),
                ('nama_ortu', models.CharField(blank=True, default='', max_length=150, verbose_name='Nama Orang Tua/Wali')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('LULUS', 'Lulus'), ('PINDAH', 'Pindah')], default='AKTIF', max_length=10, verbose_name='Status')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='akademik.kelas', verbose_name='Kelas')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
                'ordering': ['nama'],
            },
        ),
    ]
