# Generated by Django 5.0.6 on 2026-08-15 00:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kepegawaian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=10, unique=True, verbose_name='Kode')),
                ('nama_mapel', models.CharField(max_length=100, verbose_name='Nama Mata Pelajaran')),
                ('kkm', models.PositiveSmallIntegerField(default=70, verbose_name='KKM')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['nama_mapel'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=20, verbose_name='Nama Kelas')),
                ('tingkat', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Tingkat')),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=15, verbose_name='Tahun Ajaran')),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to='kepegawaian.guru', verbose_name='Wali Kelas')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'ordering': ['tingkat', 'nama_kelas'],
                'unique_together': {('nama_kelas', 'tahun_ajaran')},
            },
        ),
    ]
