# Generated by Django 5.0.6 on 2026-08-05 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=25, unique=True, verbose_name='NIP')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('no_hp', models.CharField(blank=True, default='', max_length=20, verbose_name='No. HP')),
                ('alamat', models.CharField(blank=True, default='', max_length=255, verbose_name='Alamat')),
                ('tanggal_bergabung', models.DateField(blank=True, null=True, verbose_name='Tanggal Bergabung')),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=10, unique=True, verbose_name='Kode')),
                ('nama_mapel', models.CharField(max_length=100, verbose_name='Nama Mata Pelajaran')),
                ('kkm', models.PositiveSmallIntegerField(default=70, verbose_name='KKM')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['nama_mapel'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=20, verbose_name='Nama Kelas')),
                ('tingkat', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Tingkat')),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=15, verbose_name='Tahun Ajaran')),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to='akademik.guru', verbose_name='Wali Kelas')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'ordering': ['tingkat', 'nama_kelas'],
                'unique_together': {('nama_kelas', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20, unique=True, verbose_name='NIS')),
                ('nisn', models.CharField(max_length=20, unique=True, verbose_name='NISN')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('tempat_lahir', models.CharField(blank=True, default='', max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('alamat', models.CharField(blank=True, default='', max_length=255, verbose_name='Alamat')),
                ('nama_ortu', models.CharField(blank=True, default='', max_length=150, verbose_name='Nama Orang Tua/Wali')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('LULUS', 'Lulus'), ('PINDAH', 'Pindah')], default='AKTIF', max_length=10, verbose_name='Status')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='akademik.kelas', verbose_name='Kelas')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prestasi', models.CharField(max_length=200, verbose_name='Nama Prestasi/Lomba')),
                ('tingkat', models.CharField(choices=[('SEKOLAH', 'Sekolah'), ('KECAMATAN', 'Kecamatan'), ('KABUPATEN', 'Kabupaten/Kota'), ('PROVINSI', 'Provinsi'), ('NASIONAL', 'Nasional')], default='SEKOLAH', max_length=15, verbose_name='Tingkat')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('keterangan', models.CharField(blank=True, default='', max_length=255, verbose_name='Keterangan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='akademik.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Prestasi',
                'verbose_name_plural': 'Prestasi',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_nilai', models.CharField(choices=[('HARIAN', 'Ulangan Harian'), ('UTS', 'Ujian Tengah Semester'), ('UAS', 'Ujian Akhir Semester'), ('TUGAS', 'Tugas')], default='HARIAN', max_length=10, verbose_name='Jenis Nilai')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nilai')),
                ('semester', models.CharField(choices=[('GANJIL', 'Ganjil'), ('GENAP', 'Genap')], default='GANJIL', max_length=10, verbose_name='Semester')),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=15, verbose_name='Tahun Ajaran')),
                ('tanggal_input', models.DateField(auto_now_add=True, verbose_name='Tanggal Input')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='akademik.matapelajaran', verbose_name='Mata Pelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='akademik.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
                'ordering': ['-tanggal_input'],
            },
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('SAKIT', 'Sakit'), ('IZIN', 'Izin'), ('ALPA', 'Alpa/Tanpa Keterangan')], default='HADIR', max_length=10, verbose_name='Status')),
                ('keterangan', models.CharField(blank=True, default='', max_length=255, verbose_name='Keterangan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='akademik.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Kehadiran',
                'verbose_name_plural': 'Kehadiran',
                'ordering': ['-tanggal'],
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
    ]
